language: python
cache:
  directories:
  - "$HOME/.cache/pip"

# python:
#   - "3.6"      # current default Python on Travis CI
#   - "3.7"
#   - "3.8"
#   - "3.8-dev"  # 3.8 development branch
#   # - "nightly"  # nightly build
#   - "pypy3"
# env:
#   global:
#     - BUILD_WHEEL=true
#     - BUILD_SDIST=true
#     - CIBW_BUILD="pp36* pp37* cp36?-* cp37?-*"
#     # Only build PyPy and CPython 3 (env for cibuildwheel, reference: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip)

# Build selected versions of PyPy and CPython 3 (env for cibuildwheel, reference: https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip)
matrix:
  include:
    - python: pypy3
      env: BUILD_WHEEL=true BUILD_SDIST=true CIBW_BUILD="pp36*"
    - python: 3.6
      env: BUILD_WHEEL=true BUILD_SDIST=true CIBW_BUILD="cp36?-*"
    - python: 3.7
      env: BUILD_WHEEL=true BUILD_SDIST=true CIBW_BUILD="cp37?-*"
    - python: 3.8
      services:
      - docker
      env: BUILD_WHEEL=true BUILD_SDIST=true CIBW_BUILD="cp38?-*"

# command to install dependencies
install:
  # - pip install -r requirements.txt
  # - python setup.py 
  - "./.travis/install.sh"

  # command to run tests
script:
  # - pytest
  # - python setup.py test
  - "./.travis/build.sh"

# before_deploy:
#   - ./ci/prepare_deploy.sh $PACKAGE

deploy:
  provider: releases
  file:
  - dist/*.whl
  - dist/*.tar.gz
  edge: true
  file_glob: true
  on:
    # repo: simplejson/simplejson
    tags: true
  skip_cleanup: true